OHDSI/SqlRender

java-src/org/ohdsi/sql/SqlTranslate.java
pom.xml

This pull request contains an overloaded method to ensure backwards compatibility (i.e. using the default generated sessionId)

Add overloaded method to support backwards compatibility

---

inst/csv/replacementPatterns.csv

fix of LOG10 for Redshift

---

tests/testthat/test-translateSql.R

Netezza test

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

This is to support https://github.com/OHDSI/Achilles/pull/183

Escape 'location' table name in Impala since it's a reserved word.

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

See Achilles query 109, and discussion in http://forums.ohdsi.org/t/date-support-in-impala/2599.

Fix Impala timestamp cast to handle strings.

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

https://github.com/OHDSI/Atlas/issues/418

Impala fixes for ATLAS queries.

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

Thanks to @ganisimov for assisting. Addresses https://github.com/OHDSI/Achilles/issues/232

Redshift window function replacement patterns (2nd attempt)

---

DESCRIPTION
inst/csv/replacementPatterns.csv
pom.xml
tests/testthat/test-translateSql.R

For https://github.com/OHDSI/SqlRender/issues/89

Fixed translation of Redshift window function with specified frame

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

Remove rules converting cast varchar -> TO_CHAR() for oracle.

---

R/HelperFunctions.R
R/RenderSql.R
man/loadRenderTranslateSql.Rd
man/renderSql.Rd

This provides the option to suppress missing parameter warnings.

Added warnOnMissingParameters option to renderSql and loadRenderTranslateSql

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

Fixes https://github.com/OHDSI/WebAPI/pull/442

Added rule for INSERT INTO combined with CTEs in Netezza

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

Closes https://github.com/OHDSI/SqlRender/issues/128

Added rule for INSERT INTO combined with CTEs in Redshift

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

Fixes https://github.com/OHDSI/SqlRender/issues/131

Added translation for indexes in Impala

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

The origin ticket is https://github.com/OHDSI/WebAPI/issues/583

Added rule for default constraint (pdw)

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

Closes #147 
related to https://github.com/OHDSI/WebAPI/issues/749

ISNUMERIC added for Impala, Netezza & BigQuery

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

fixes https://github.com/OHDSI/SqlRender/issues/154

Fixed isNumeric for BQ

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

fixes https://github.com/OHDSI/SqlRender/issues/165

Fixes isNumeric check for Netezza

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

Fixes https://github.com/OHDSI/WebAPI/issues/1037

Added translation for index in oracle

---

java/org/ohdsi/sql/SqlRender.java
tests/testthat/test-renderSql.R

support for dollar sign in substituted values was added

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

resolves Netezza select into

---

pom.xml

Fixes pom.xml per OHDSI/ArachneCommons#225

Remove Maven Central Reference

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

fixes https://github.com/OHDSI/SqlRender/issues/211

(BigQuery) Date format for string cast is changed to '%Y%m%d'

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

fixes https://github.com/OHDSI/SqlRender/issues/211

Cast now checks the type of input

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translateSql.R

Add pattern for "UPDATE STATISTICS" statement

Update statistics bq

---

inst/csv/replacementPatterns.csv

Resolves https://github.com/OHDSI/Achilles/issues/465

fix EOMONTH for Oracle

---

tests/testthat/test-translate-spark.R

Instead, now using dummy values. Locally, all spark tests passed for me. 
Fixes #253

Removed parameterized elements of Spark unit tests

---

inst/csv/replacementPatterns.csv

Fixes #255 with new replacement pattern

Add CEILING replacement for SQLite

---

README.md

Small docs PR based on issue #279 to let users know that they should use v4 of R.

Added small note in README about R v4

---

inst/csv/replacementPatterns.csv
inst/csv/supportedDialects.csv
tests/testthat/test-translate-duckdb.R

Before you do a pull request, you should always **file an issue** and make sure the package maintainer agrees that it’s a problem, and is happy with your basic proposal for fixing it. We don’t want you to spend a bunch of time on something that we don’t think is a good idea.
Additional requirements for pull requests:
- Adhere to the [Developer Guidelines](https://ohdsi.github.io/MethodsLibrary/developerGuidelines.html) as well as the [OHDSI Code Style](https://ohdsi.github.io/MethodsLibrary/codeStyle.html).
- If possible, add unit tests for new functionality you add.
- Restrict your pull request to solving the issue at hand. Do not try to 'improve' parts of the code that are not related to the issue. If you feel other parts of the code need better organization, create a separate issue for …

Duck db support

---

DESCRIPTION
inst/csv/replacementPatterns.csv

solves #301 
Error appeared when runing 
https://github.com/OHDSI/PheValuator/blob/7ee493f4628ee71e635fb98dd3dca5a78446dc07/inst/sql/sql_server/GetxSpecCount.sql
Adding this translation fixed the problem

added NEWID traslation for BigQuery

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translate-snowflake.R

Addition of rewrite rule for snowflake to fix: #317

Translate WITH INSERT into INSERT WITH for Snowflake

---

inst/csv/replacementPatterns.csv

After this fix the following issue 
https://github.com/OHDSI/DataQualityDashboard/issues/424 
got resolved

added charindex translation for bq

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translate-netezza.R

Added several replacements for "Drop table" statement in netezza

Adding missed "drop table" statements for Netezza

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translate-snowflake.R

I created new PR, my fork was out of sync with base repository. Attempt to sync it closed PR.

Snowflake `ceiling()`

---

inst/csv/replacementPatterns.csv
tests/testthat/test-translate-duckdb.R

fix duckdb adding years + test
